name: dolfyn-dev
channels:
  - defaults
dependencies:
  - pip
  - python>=3.6
  - pip:
    - h5netcdf>=0.11.0
    - h5py>=3.3.0
    - numpy>=1.21.1
    - pandas>=1.3.1
    - python-dateutil>=2.8.2
    - pytz>=2021.1
    - scipy>=1.7.0
    - six>=1.16.0
    - xarray>=0.19.0
