name: readthedocs
channels:
  - defaults
dependencies:
  - pip
  - python>=3.6
  - pip:
    - alabaster>=0.7.12
    - atomicwrites>=1.4.0
    - attrs>=21.2.0
    - babel>=2.9.1
    - charset-normalizer>=2.0.3
    - colorama>=0.4.4
    - coverage>=5.5
    - docutils>=0.16
    - netcdf4>=1.5.7
    - idna>=3.2
    - imagesize>=1.2.0
    - iniconfig>=1.1.1
    - jinja2>=3.0.1
    - markupsafe>=2.0.1
    - nose>=1.3.7
    - numpy>=1.21.1
    - packaging>=21.0
    - pandas>=1.3.0
    - pluggy>=0.13.1
    - py>=1.10.0
    - pygments>=2.9.0
    - pyparsing>=2.4.7
    - pytest>=6.2.4
    - python-dateutil>=2.8.2
    - pytz>=2021.1
    - requests>=2.26.0
    - scipy>=1.7.0
    - six>=1.16.0
    - snowballstemmer>=2.1.0
    - sphinx>=4.1.1
    - sphinx-rtd-theme>=0.5.2
    - sphinxcontrib-applehelp>=1.0.2
    - sphinxcontrib-devhelp>=1.0.2
    - sphinxcontrib-htmlhelp>=2.0.0
    - sphinxcontrib-jsmath>=1.0.1
    - sphinxcontrib-qthelp>=1.0.3
    - sphinxcontrib-serializinghtml>=1.1.5
    - toml>=0.10.2
    - urllib3>=1.26.6
    - xarray>=0.18.2
    - nbsphinx